language: java
sudo: false
install: true
jdk: openjdk11


before_cache:
  # remove all the artifacts that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/com.socientegenerale.sonar.openapi
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

# to keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar'
    - '$HOME/jvmr'
    - '$HOME/maven'

notifications:
  email: false

addons:
  sonarcloud:
    organization: "societe-generale"

script: 
  - mvn -Pcoverage,release --settings release/mvnsettings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.projectKey=societe-generale_sonar-openapi

before_install:
  - release/createReleaseProperties.sh
  # Install GPG secrets so that we can sign during the release
  - echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
  - echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
